### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by nelsinofrancisco** [nelsinofrancisco/ruby-catalog-capstone#21]
# Ruby group capstone: set up your Kanban board

We've set up the Kanban Board, divided tasks between the members, and estimated the time to complete them.
Here's our [Projects](https://github.com/nelsinofrancisco/ruby-catalog-capstone/projects)

## Notes:

- There are 3 members in this group; 
- @nelsinofrancisco is Student 1;
- @mateo951 is Student 2;
- @Felipeg005 is Student 3;

## Requirements:

- [x] Open the GitHub project (Kanban board) in your team repo.
- [x] Open project requirements and read them carefully.
- [x] Open project requirements divided by team members and compare them with the project requirements.
- [x] Create tasks on your Kanban board based on the project requirements divided by team member.
- [x] Each task should be a separate card that:
  - Has a descriptive title.
  - Has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
  - Has a description of the task.
- [x] Each of the team members should assign themselves to the cards as divided in the project requirements divided by team member (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

**Comment by henatan99** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] @nelsinofrancisco , I think there are a few tasks you have missed. You didn't include tasks related to the `Label` class. Kindly add the missed tasks. 

- [ ] @mateo951 , you have a task with the title of `create classes`. I think it is better to be more explicit like `create Music Album class`, `creat Genre class` etc... In addition, I think you should also add a task for the `options` of data retrieval. 

- [ ] @Felipeg005 , you also have a task with the title of `create class files`. I think it is better to be more explicit like `create Music Album class`, `creat Genre class` etc... In addition, I think you should also add a task for the `options` of data retrieval. 

- [ ] Hey team, most of the group tasks are not covered in your Kanban board. Kindly cover the tasks and make sure it is explicit. 
![image](https://user-images.githubusercontent.com/64894927/143913458-4dd0d350-6258-4746-91e7-908a4d1f308a.png)

![image](https://user-images.githubusercontent.com/64894927/143913520-8b18f008-1834-43ef-9601-5fa59bda5b53.png)




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by henatan99** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] @nelsinofrancisco , I think there are a few tasks you have missed. You didn't include tasks related to the `Label` class. Kindly add the missed tasks. 

- [ ] @mateo951 , you have a task with the title of `create classes`. I think it is better to be more explicit like `create Music Album class`, `creat Genre class` etc... In addition, I think you should also add a task for the `options` of data retrieval. 

- [ ] @Felipeg005 , you also have a task with the title of `create class files`. I think it is better to be more explicit like `create Music Album class`, `creat Genre class` etc... In addition, I think you should also add a task for the `options` of data retrieval. 

- [ ] Hey team, most of the group tasks are not covered in your Kanban board. Kindly cover the tasks and make sure it is explicit. 
![image](https://user-images.githubusercontent.com/64894927/143913458-4dd0d350-6258-4746-91e7-908a4d1f308a.png)

![image](https://user-images.githubusercontent.com/64894927/143913520-8b18f008-1834-43ef-9601-5fa59bda5b53.png)




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nelsinofrancisco** [comment]
Dear @henatan99, 

I agree with you about the descriptive names and I'm gonna change that before I post this comment, but we really don't want to add a task for every little thing we have to do. We as a team discussed how we would divide the tasks into similar groups. So when we have Create Class files we wanted to create the classes that we need from the UML diagram and add the IV that are required, methods, and so on. If you see my latest [PR](https://github.com/nelsinofrancisco/ruby-catalog-capstone/pull/23) you can see that I'm creating the Label class on that Card too. 

To Clarify our work division:

- Student X:
- Card 1: Create [class_name] & [class_name] classes => The student should create the files and define variables shown at the UML diagram;
- Card 2: Implement Methods for [class_name] &  [class_name] => The student should write logic for the methods present in UML diagram;
- Card 3: Write Unit Tests for [class_name] &  [class_name] => The student should write tests for all methods present in these classes;
- Card 4: Implement [collection_name] methods in the console.app => The student should write the required methods in the main.rb file;
- Card 5: Preserve Data in JSON for [collection_name] => The student should generate a file in JSON format that saves the state of that collection;
- Card 6: Add schema.sql for  [class_name] &  [class_name]

**Comment by nelsinofrancisco** [comment]
I hope this clarifies the issue. I also Updated all Cards to show clearly what Tasks we're doing in each card, an idea by @Felipeg005.  ;)

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nelsinofrancisco** [comment]
@mikethreels, @henatan99, @mateo951, @Felipeg005 Issue Closed.
